language: node_js
node_js:
- node
script:
- yarn test:unit
- yarn build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: awsugramteam14
  skip_cleanup: true
  region: ca-central-1
  acl: public_read
  local_dir: dist
  
